project_id = "scjwymsygllanubzfbok"

[functions.send-daily-question]
verify_jwt = false

[functions.send-email]
verify_jwt = false

[functions.webhook-processor]
verify_jwt = false

[functions.generate-report]
verify_jwt = true